version: "3.8"
services:
  user_service:
    build: ./services/user
    container_name: social_fusion_user_service
    command:
    - sh
    - -c
    - |
      php migrate.php
      php -S 0.0.0.0:8800
    ports:
    - 8800:8800
    environment:
      DB_HOST:                 db
      DB_ROOT_PASS:            ${DB_ROOT_PASS}
      DB_NAME:                 ${DB_NAME}
      DB_USER:                 ${DB_USER}
      DB_PASS:                 ${DB_PASS}
    volumes:
    - ./services/user:/var/www/html
    depends_on:
    - db

  post_service:
    build:
      context: ./services/post
      target: build
    container_name: social_fusion_post_service
    command:
    - sh
    - -c
    - |
      dotnet restore
      dotnet tool restore
      dotnet ef database update
      dotnet run
    ports:
    - 5146:5146
    environment:
      DB_HOST:                 db
      DB_NAME:                 ${DB_NAME}
      DB_USER:                 ${DB_USER}
      DB_PASS:                 ${DB_PASS}
    volumes:
    - ./services/post:/src
    depends_on:
    - db

  db:
    image: mariadb:latest
    container_name: social_fusion_db
    environment:
      MYSQL_ROOT_PASSWORD:     ${DB_ROOT_PASS}
      MYSQL_DATABASE:          ${DB_NAME}
      MYSQL_USER:              ${DB_USER}
      MYSQL_PASSWORD:          ${DB_PASS}
    volumes:
    - ./db:/var/lib/mysql
    ports:
    - 3306:3306
