version: "3.8"
services:
  db:
    image: mariadb:latest
    container_name: social_fusion_db
    environment:
      MYSQL_ROOT_PASSWORD:     ${DB_ROOT_PASS}
      MYSQL_DATABASE:          ${DB_NAME}
      MYSQL_USER:              ${DB_USER}
      MYSQL_PASSWORD:          ${DB_PASS}
    volumes:
    - ./db:/var/lib/mysql
    ports:
    - 3306:3306
