version: "3.8"
services:
  user_service:
    build: ./services/user
    container_name: social_fusion_user_service
    command: php -S 0.0.0.0:8800
    ports:
    - 8800:8800
    volumes:
    - ./services/user:/app
    depends_on:
    - db

  db:
    image: mariadb:latest
    container_name: social_fusion_db
    environment:
      MYSQL_ROOT_PASSWORD:     ${DB_ROOT_PASS}
      MYSQL_DATABASE:          ${DB_NAME}
      MYSQL_USER:              ${DB_USER}
      MYSQL_PASSWORD:          ${DB_PASS}
    volumes:
    - ./db:/var/lib/mysql
    ports:
    - 3306:3306
